name: Ejecutar tarea diaria del bot

on:
  schedule:
    - cron: '0 14 * * *'  # 8am hora de México (CDMX es UTC-6)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar navegadores de Playwright
        run: |
          playwright install --with-deps

      - name: Ejecutar tarea diaria
        run: python daily_task.py
